Created react login modal
danielanatolie/mecollect pull request #14
Opened 2019-01-27 19:57 UTC by sinfran

2019-02-03 05:07 UTC, danielanatolie requested changes

2019-02-03 05:07 UTC, danielanatolie commented on server.js
> +const port = process.env.PORT || 3000;
The client-side is served on port 3000 and proxies all requests to 5000, why did you change the server port?

2019-02-03 05:29 UTC, sinfran commented on server.js
> +const port = process.env.PORT || 3000;
Oh sorry that shouldn’t have been changed, I was trying to debug something and forgot to change it back

2019-02-03 20:49 UTC, danielanatolie commented on server.js
> +const port = process.env.PORT || 3000;
Do you mind changing it back, so we can close the PR

2019-02-04 00:24 UTC, sinfran commented on server.js
> +const port = process.env.PORT || 3000;
Done

2019-02-04 02:05 UTC, danielanatolie approved these changes

2019-02-04 02:05 UTC, merged